---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/clients":
    get:
      summary: list all clients
      description: Get a list of all clients / with phone / with email
      tags:
      - Clients
      parameters:
      - name: phone
        in: query
      - name: email
        in: query
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/dateavailabilities":
    get:
      summary: list dateavailabilities
      description: Get all available dates to schedule
      tags:
      - Date Availability
      responses:
        '200':
          description: successful
  "/schedules":
    get:
      summary: list schedules
      description: Get a list of schedules
      tags:
      - Schedules
      responses:
        '200':
          description: successful
    post:
      summary: create schedule
      description: Create schedules
      tags:
      - Schedules
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_firstname:
                  type: string
                client_lastname:
                  type: string
                client_phone:
                  type: string
                client_email:
                  type: string
                contact_concent:
                  type: boolean
                vin:
                  type: string
                vehicle_brand:
                  type: string
                vehicle_name:
                  type: string
                licence_number:
                  type: string
                make_year:
                  type: string
                purchased_date:
                  type: string
                warrenty_date:
                  type: string
                insurance_details:
                  type: string
                service_date:
                  type: string
                timeslot_id:
                  type: string
                purpose:
                  type: string
              required:
              - client_firstname
              - client_lastname
              - client_phone
              - client_email
              - vin
              - service_date
              - timeslot_id
              - purpose_id
  "/schedules/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    put:
      summary: update schedule
      description: Update schedules
      tags:
      - Schedules
      responses:
        '200':
          description: successful
  "/vehicles":
    get:
      summary: list all vehicles
      description: Get a list of all vehicles / with licence_number / with vin
      tags:
      - Vehicles
      parameters:
      - name: licence_number
        in: query
      - name: vin
        in: query
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
